"""empty message

Revision ID: 040f0d95a7c7
Revises: f09abfff24aa
Create Date: 2023-02-02 15:04:40.606346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040f0d95a7c7'
down_revision = 'f09abfff24aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
